wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [40, 40]
    rows: [13, 13, 4]
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        UTC: "Etc/UTC"
        London: "Europe/London"
        New York: "America/New_York"
        San Francisco: "America/Los_Angeles"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    security:
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 3600
    status:
      enabled: false
      position:
        top: 2
        left: 0
        height: 1
        width: 2
      refreshInterval: 1
    system:
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 3600
    textfile:
      enabled: true
      filePath: "~/.wtf/config.yml"
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 30
    gcal:
      colors:
        title: "red"
        description: "lightblue"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet\ ', 'lightseagreen']
        - ['lunch', 'yellow']
        past: "gray"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "your.email@example.com"
      enabled: true
      eventCount: 12
      position:
        top: 2
        left: 0
        height: 2
        width: 1
      refreshInterval: 300
      secretFile: "~/.wtf/gcal/client_secret.json"
      withLocation: true
    weather:
      # From http://openweathermap.org/help/city_list.txt
      cityids:
      - 5128581 # NYC
      - 6058560 # London
      - 5391959 # San Francisco
      colors:
        current: "lightblue"
      enabled: true
      language: "EN"
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 90
      tempUnit: "C"
