#!/bin/sh

mkdir -p ~/.dotfiles/vim/cache/info
git update-index --assume-unchanged ~/.dotfiles/vim/cache/info

# Install homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew tap homebrew/versions
brew tap homebrew/services

# Symlink all the things
ln -s ~/.dotfiles/npm/.npmrc ~/.npmrc
ln -s ~/.dotfiles/bash/.bash_profile ~/.bash_profile
ln -s ~/.dotfiles/git/.gitignore ~/.gitignore
ln -s ~/.dotfiles/git/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/tmux/.tmux.conf ~/.tmux.conf
ln -s ~/.dotfiles/vim/.vimrc ~/.vimrc
ln -s ~/.dotfiles/fonts/* ~/Library/Fonts/
rm -rf ~/.ssh; ln -s ~/Dropbox/.ssh ~/.ssh

# General desktop apps
brew cask install google-chrome
brew cask install spotify
brew cask install spotify-notifications
brew cask install slack
brew cask install sequel-pro
brew cask install iterm2
brew cask install skype
brew cask install sublime-text
brew cask install transmission
brew cask install spectacle
brew cask install vagrant
brew cask install virtualbox
brew install awscli
brew install aws-elasticbeanstalk
brew install tmux
brew install node
brew install reattach-to-user-namespace --with-wrap-launchctl # Make sure LaunchCtl works inside Tmux
brew install gcc48
brew install python3
brew install ctags            # Exuberant ctags
brew install the_silver_searcher
brew install mongodb
brew install memcached
brew install mariadb
brew install redis
brew install elasticsearch
brew install ghi              # Github issues (when npm gh is better, remove)
brew install hub              # Hub from github
brew install httpie

# Start Services
brew services start mongodb

# NPM
sudo npm cache clean -f
sudo npm install -g n
sudo n 4.*

npm -g install aglio
npm -g install drafter
npm -g install gh        # More github functionality
npm -g install instant-markdown-d

# Python things
sudo pip install Pygments
pip3 install todocli     # Todo list

# Vagrant things
vagrant plugin install vagrant-hostsupdater

# Sort out my .dotfiles dependencies etc
git clone git@github.com:rupa/z.git ~/.dotfiles/scripts/z
git clone git@github.com:micha/resty.git ~/.dotfiles/scripts/resty

source ~/.bash_profile

# php things
brew install homebrew/php/php70 --with-fpm
brew install php70-mcrypt
brew install homebrew/php/php70-memcached
brew install php70-mongodb
brew install php70-xdebug
brew install phpunit
brew install php-code-sniffer
brew install php-cs-fixer
brew install phpmd

# Temporarily set up PHP paths (normally in .bash_profile)
export PATH="$(brew --prefix homebrew/php/php70)/bin:$PATH"
export PATH=~/.composer/vendor/bin:$PATH

# Composer
curl https://getcomposer.org/installer | php; mv composer.phar /usr/local/bin/composer

# Laravel Valet
composer global require laravel/valet
valet install
(cd ~/Sites && valet park)
valet start

# Blackfire
brew tap blackfireio/homebrew-blackfire
brew install blackfire-agent
sudo blackfire-agent -register
ln -sfv /usr/local/opt/blackfire-agent/*.plist ~/Library/LaunchAgents
launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.blackfire-agent.plist
blackfire config
brew install blackfire-php55

