#!/bin/bash

OUTPATH="${HOME}/.local-cert"

mkdir -p "$OUTPATH"

cat << EOF > "${OUTPATH}/ssl.conf"
[ req ]
default_bits       = 4096
distinguished_name = req_distinguished_name
req_extensions     = req_ext
prompt = no

[ req_distinguished_name ]
C=US
ST=New York
L=New York
O=localhost
OU=localhost
CN=localhost

[ req_ext ]
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = 127.0.0.1
IP.1 = 127.0.0.1
EOF

echo "Generate private key"
openssl genrsa -out "${OUTPATH}/private.key" 4096

echo "Generate a Certificate Signing Request"
openssl req -new -sha256 \
	-out "${OUTPATH}/private.csr" \
	-key "${OUTPATH}/private.key" \
	-config "${OUTPATH}/ssl.conf"

echo "Generate the certificate"
openssl x509 -req \
	-days 3650 \
	-in "${OUTPATH}/private.csr" \
	-signkey "${OUTPATH}/private.key" \
	-out "${OUTPATH}/private.crt" \
	-extensions req_ext \
	-extfile "${OUTPATH}/ssl.conf"

echo "Add the certificate to keychain and trust it"
sudo security add-trusted-cert -d \
	-r trustRoot -k /Library/Keychains/System.keychain \
	"${OUTPATH}/private.crt"

echo "Create a pem file from crt"
openssl x509 \
	-in "${OUTPATH}/private.crt" \
	-out "${OUTPATH}/private.pem" \
	-outform PEM

rm "${OUTPATH}/ssl.conf"
