#!/bin/bash

source ~/.dotfiles/Setup/sudo-no-root
source ~/.dotfiles/Setup/xcode
source ~/.dotfiles/Setup/homebrew
source ~/.dotfiles/Setup/osx-preferences
source ~/.dotfiles/Setup/cleanup-dock
source ~/.dotfiles/Setup/restart-osx-services
source ~/.dotfiles/Setup/open-applications
source ~/.dotfiles/Setup/php-composer
source ~/.dotfiles/Setup/local-certificates
source ~/.dotfiles/Setup/fzf
source ~/.dotfiles/Setup/yarn-global
source ~/.dotfiles/Setup/symlinks
source ~/.dotfiles/Setup/ssh
source ~/.dotfiles/Setup/vim-setup
source ~/.dotfiles/Setup/tmux-setup
source ~/.dotfiles/Setup/docker
source ~/.dotfiles/Setup/osx-default-apps
source ~/.dotfiles/Setup/osx-finder-shortcuts

sudo /usr/local/opt/mysql/bin/mysql.server stop

# This repo
echo "Setting remote URL for this dotfiles repo"
git remote set-url origin git@github.com:benswinburne/dotfiles.git

source ~/.dotfiles/.bash_profile

# Clean up
read -pr "Cleaning up Brew (any key)"
brew update
brew cleanup

printf "protocol=https\\nhost=github.com\\n" | git credential-osxkeychain erase

# Add the new shell to the list of allowed shells
# sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'
# Change to the new shell
_USER=$(whoami)
sudo chsh -s /usr/local/bin/bash "$_USER"

# Bye itunes (hopefully?!)
# sudo chmod -x /Applications/Music.app

# sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist # Disable spotlight
#(cd /System/Library/CoreServices/; sudo mv Search.bundle/ Search2.bundle)
# sudo chmod 600 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search
# /usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c \
#   "Set AppleSymbolicHotKeys:64:enabled false"


# read -p "Pip installations"
# # pip install howdoi --user
# # pip install cfn-lint --user # cfn linting
# # pip install websocket-client
pip3 install --user localstack
pip3 install --user awscli-local

# english-dictionary-cli \
#zmq
# https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md

# MySQL
# ---------------
# mysql_secure_installation
# mysql_upgrade -u root

# Fonts
# cp ~/.dotfiles/fonts/* ~/Library/Fonts/.

# Disable crash reporting service
# launchctl unload -w /System/Library/LaunchAgents/com.apple.ReportCrash.plist
# sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.ReportCrash.Root.plist
