#!/usr/bin/env bash

brew install dockutil

# Clean up the default dock programs
for app in \
  'Launchpad' \
  'Safari' \
  'Messages' \
  'Mail' \
  'Maps' \
  'FaceTime' \
  'Calendar' \
  'Contacts' \
  'Reminders' \
  'Notes' \
  'Freeform' \
  'TV' \
  'Music' \
  'News' \
  'App Store' \
  'System Preferences' \
  'System Settings' \
  'iPhone Mirroring' \
  'iBooks' \
  'Photos' \
  'Siri' \
  'Downloads' \
  'Numbers' \
  'Keynote' \
  'Pages' \
  'Podcasts'; do
  dockutil --remove "$app" --allhomes 2>/dev/null
done

dockutil --add /Applications/Google\ Chrome.app --position 1
dockutil --add /Applications/Ghostty.app --position 2
dockutil --add /Applications/Slack.app --position 4

brew uninstall dockutil
