#!/usr/bin/env bash

echo "Setup Docker"

# Bash completions
mkdir -p ~/.local/share/bash-completion/completions
docker completion bash > ~/.local/share/bash-completion/completions/docker

# ECR credentials from Dropbox
mkdir -p ~/.docker
ln -sf ~/Dropbox/.docker/config.json ~/.docker/config.json

mkdir -p ~/.docker/cli-plugins
ln -sfn $(brew --prefix)/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
ln -sfn $(brew --prefix)/opt/docker-buildx/bin/docker-buildx ~/.docker/cli-plugins/docker-buildx

colima start

brew services start colima

