#!/bin/bash

source ~/.dotfiles/Setup/sudo-no-root

# install homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
	echo "Installing Homebrew"
  /usr/bin/ruby -e \
  	"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# now OSX defaults to zsh, and it's not in our path yet
# echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/ben/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

/usr/sbin/softwareupdate --install-rosetta --agree-to-license

# HOMEBREW_NO_AUTO_UPDATE=1
echo "Installing Homebrew Bundle"
brew bundle
brew bundle cleanup --force
# HOMEBREW_NO_AUTO_UPDATE=0

softwareupdate --all --install --force
