#!/usr/bin/env bash

# https://blog.filippo.io/mkcert-valid-https-certificates-for-localhost/

echo "Local Certificate Setup"

mkdir -p ~/.localcert
cd ~/.localcert

mkcert localhost 127.0.0.1 0.0.0.0 "*.eu.ngrok.io" "*.ngrok.io"
mkcert -install
mv localhost+4.pem localhost.pem
mv localhost+4-key.pem localhost-key.pem
