#!/usr/bin/env bash

open /Applications/Docker.app/
open /Applications/Flux.app/
open /Applications/KeepingYouAwake.app/
open /Applications/Dropbox.app/
open /Applications/Alfred\ 4.app/
open /Applications/Muzzle.app/
open /Applications/Rectangle.app/
open /Applications/Firefox.app/ # Required for certificate creation to work
