#!/usr/bin/env bash

open /Applications/Docker.app/
open /Applications/Flux.app/
open /Applications/KeepingYouAwake.app/
open /Applications/Dropbox.app/
open /Applications/Alfred\ 5.app/
open /Applications/Muzzle.app/
open /Applications/Rectangle.app/
open /Applications/Bitwarden.app/
open /Applications/Ice.app/
open /Applications/Docker\ Desktop.app/
open /Applications/Bearded\ Spice.app/
open /Applications/Firefox.app/ # Required for certificate creation to work
