#!/usr/bin/env bash
# vi:syntax=sh

source ~/.dotfiles/Setup/sudo-no-root

# Sensible Mac Defaults

echo "Configuring MacOS defaults"

## Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Disable transparency in the menu bar and elsewhere on Yosemite
# defaults write com.apple.universalaccess reduceTransparency -bool true

# Scrollbars setup
# Possible values: `WhenScrolling`, `Automatic` and `Always`
defaults write NSGlobalDomain AppleShowScrollBars -string "WhenScrolling"

# Disable the over-the-top focus ring animation
defaults write NSGlobalDomain NSUseAnimatedFocusRing -bool false

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Remove duplicates in the “Open With” menu (also see `lscleanup` alias)
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

# Set language and text formats
defaults write NSGlobalDomain AppleLanguages -array "en"
defaults write NSGlobalDomain AppleLocale -string "en_GB@currency=GBP"
defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
defaults write NSGlobalDomain AppleMetricUnits -bool true
defaults write com.apple.TextInputMenu visible -bool false # disables the input menu in the menu bar
# https://gist.github.com/talkingmoose/861588c136f5946d6961e41c51f2cb93
# https://github.com/mathiasbynens/custom.keylayout/issues/7

# Save screenshots to the desktop
defaults write com.apple.screencapture location -string "${HOME}/Desktop"

# Hide the menu bar
defaults write NSGlobalDomain _HIHideMenuBar -bool true

# Dark interface
defaults write NSGlobalDomain AppleInterfaceStyle Dark

# Coding bits
# -----------

# Disable automatic capitalization
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable smart dashes
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Disable automatic period substitution
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# SSD-specific tweaks
# -------------------

# Disable hibernation (speeds up entering sleep mode)
sudo pmset -a hibernatemode 0

# Remove the sleep image file to save disk space
# sudo rm /private/var/vm/sleepimage
# Create a zero-byte file instead…
# sudo touch /private/var/vm/sleepimage
# …and make sure it can’t be rewritten
# sudo chflags uchg /private/var/vm/sleepimage

# Mouse & Keyboard
# ----------------

# Enable tap to click (Trackpad) for this user and for the login screen
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true # trackpad
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true # bluetooth trackpad

# Right click right side of mouse
defaults write "com.apple.driver.AppleBluetoothMultitouch.mouse" "MouseButtonMode" 'TwoButton'
defaults write "com.apple.AppleMultitouchMouse" "MouseButtonMode" 'TwoButton'
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseTwoFingerHorizSwipeGesture -int 0
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1 # tap to click at login screen

# single finger swipe left
defaults write "com.apple.AppleMultitouchMouse" "MouseTwoFingerHorizSwipeGesture" '0'
defaults write "Apple Global Domain" "AppleEnableMouseSwipeNavigateWithScrolls" '1'

# don't open mission control with tap two fingers
defaults write "com.apple.driver.AppleBluetoothMultitouch.mouse" "MouseTwoFingerDoubleTapGesture" '0'
defaults write "com.apple.AppleMultitouchMouse" "MouseTwoFingerDoubleTapGesture" '0'

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# Stop iTunes from responding to the keyboard media keys
launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null

# Audio
# -----

# Increase sound quality for Bluetooth headphones/headsets
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40


# Screensaver
# -----------

echo "Configuring Screensaver"

# Lock screen using bottom left hotcorner
defaults write com.apple.dock wvous-bl-corner -int 10

# Activate screen saver using bottom right hotcorner
defaults write com.apple.dock wvous-br-corner -int 5

defaults -currentHost write com.apple.screensaver idleTime 300
defaults -currentHost write com.apple.screensaver CleanExit -bool true
defaults -currentHost write com.apple.screensaver \
  moduleDict -dict moduleName Aerial path \
    "${HOME}/Library/Screen Savers/Aerial.saver" type 0

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Screen
# ------

# Enable subpixel font rendering on non-Apple LCDs
# Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
defaults write NSGlobalDomain AppleFontSmoothing -int 1

# Finder
# ------

# Allow quitting via ⌘ + Q; doing so will also hide desktop icons
defaults write com.apple.finder QuitMenuItem -bool true

# Finder: disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Set Desktop as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfDe"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"

# Show icons for hard drives, servers, and removable media on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowMountedServersOnDesktop -bool false
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false

# Finder: show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Enable spring loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

# Remove the spring loading delay for directories
# defaults write NSGlobalDomain com.apple.springing.delay -float 0

# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`, `Nlsv`
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

# Disable the warning before emptying the Trash
# defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Dock & Dashboard
# ----------------

# Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -bool true

# Enable spring loading for all Dock items
defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

# Show indicator lights for open applications in the Dock
defaults write com.apple.dock show-process-indicators -bool true

# Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
#defaults write com.apple.dock persistent-apps -array

# Show only open applications in the Dock
#defaults write com.apple.dock static-only -bool true

# Don’t animate opening applications from the Dock
defaults write com.apple.dock launchanim -bool false

# Speed up Mission Control animations
defaults write com.apple.dock expose-animation-duration -float 0.1

# Don’t group windows by application in Mission Control
# (i.e. use the old Exposé behavior instead)
defaults write com.apple.dock expose-group-by-app -bool false

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

# Don’t show Dashboard as a Space
defaults write com.apple.dock dashboard-in-overlay -bool true

# Don’t automatically rearrange Spaces based on most recent use
# defaults write com.apple.dock mru-spaces -bool false

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0

# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Make Dock icons of hidden applications translucent
defaults write com.apple.dock showhidden -bool true

# Don’t show recent applications in Dock
defaults write com.apple.dock show-recents -bool false

# Disable the Launchpad gesture (pinch with thumb and three fingers)
defaults write com.apple.dock showLaunchpadGestureEnabled -int 0

# Reset Launchpad, but keep the desktop wallpaper intact
find "${HOME}/Library/Application Support/Dock" -name "*-*.db" -maxdepth 1 -delete
defaults write com.apple.dock ResetLaunchPad -bool true #; killall Dock

# Set the icon size of Dock items to 36 pixels
defaults write com.apple.dock tilesize -int 30

# Spotlight
# ---------

# Hide Spotlight tray-icon (and subsequent helper)
# sudo chmod 600 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search

# Load new settings before rebuilding the index
killall mds > /dev/null 2>&1
# Make sure indexing is enabled for the main volume
sudo mdutil -i on / > /dev/null
# Rebuild the index from scratch
sudo mdutil -E / > /dev/null

# TextEdit & Misc
# ---------------

echo "Configuring TextEdit & Misc"

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0
# Open and save files as UTF-8 in TextEdit
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

# Prevent Photos from opening automatically when devices are plugged in
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

# Disable smart quotes as it’s annoying for messages that contain code
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false


# Updates
# -------

echo "Configuring Automatic Updates"

# Enable the automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Download newly available updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# Install System data files & security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

# Automatically download apps purchased on other Macs
defaults write com.apple.SoftwareUpdate ConfigDataInstall -int 1

# Turn on app auto-update
defaults write com.apple.commerce AutoUpdate -bool true

# Allow the App Store to reboot machine on macOS updates
defaults write com.apple.commerce AutoUpdateRestartRequired -bool false

# Transmission
# ------------

# # Use `~/Downloads/Torrents/.incomplete` to store incomplete downloads
# defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true
# defaults write org.m0k.transmission IncompleteDownloadFolder -string "${HOME}/Downloads/Torrents/.incomplete"

# # Use `~/Downloads` to store completed downloads
# defaults write org.m0k.transmission DownloadLocationConstant -bool true
# defaults write org.m0k.transmission DownloadFolder -string "${HOME}/Downloads/Torrents"

# # Don’t prompt for confirmation before downloading
# defaults write org.m0k.transmission DownloadAsk -bool false
# defaults write org.m0k.transmission MagnetOpenAsk -bool false

# # Don’t prompt for confirmation before removing non-downloading active transfers
# defaults write org.m0k.transmission CheckRemoveDownloading -bool true

# # Trash original torrent files
# defaults write org.m0k.transmission DeleteOriginalTorrent -bool true

# # Hide the donate message
# defaults write org.m0k.transmission WarningDonate -bool false
# # Hide the legal disclaimer
# defaults write org.m0k.transmission WarningLegal -bool false

# # IP block list.
# # Source: https://giuliomac.wordpress.com/2014/02/19/best-blocklist-for-transmission/
# defaults write org.m0k.transmission BlocklistNew -bool true
# defaults write org.m0k.transmission BlocklistURL -string "https://github.com/sahsu/transmission-blocklist/releases/latest/download/blocklist.gz"
# defaults write org.m0k.transmission BlocklistAutoUpdate -bool true

# # Randomize port on launch
# defaults write org.m0k.transmission RandomPort -bool true

# # Ratio Checks
# defaults write org.m0k.transmission RatioCheck -int 1
# defaults write org.m0k.transmission RatioLimit -string "0.01"
# defaults write org.m0k.transmission CheckUpload -int 1
# defaults write org.m0k.transmission UploadLimit -int 5
# defaults write org.m0k.transmission RemoveWhenFinishSeeding -int 1

# Iterm
# -----
# defaults write com.googlecode.iterm2 PrefsCustomFolder "${HOME}/.dotfiles/iterm"
# defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
# defaults write com.googlecode.iterm2 UseLionStyleFullscreen -int 0

# Preference Files
echo "Symlinking preferences"
# https://github.com/asmeurer/prefsync ?
ln -sf ~/.dotfiles/Preferences/com.knollsoft.Rectangle.plist ~/Library/Preferences/com.knollsoft.Rectangle.plist
ln -sf ~/.dotfiles/Preferences/com.apple.Siri.plist ~/Library/Preferences/com.apple.Siri.plist
ln -sf ~/.dotfiles/Preferences/org.herf.Flux.plist ~/Library/Preferences/org.herf.Flux.plist
ln -sf ~/.dotfiles/Preferences/org.m0k.transmission.plist ~/Library/Preferences/org.m0k.transmission.plist
ln -sf ~/.dotfiles/Preferences/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist

# Rectangle
# defaults write com.knollsoft.Rectangle alternateDefaultShortcuts -bool true

# Unquarantine Quicklook application
sudo xattr -cr ~/Library/QuickLook/QLStephen.qlgenerator
sudo xattr -cr ~/Library/QuickLook/*.qlgenerator
qlmanage -r
qlmanage -r cache

# Kill affected applications
# --------------------------

echo "Killing affected applications"
for app in "Activity Monitor" \
	"Calendar" \
	"cfprefsd" \
	"Dock" \
	"Rectangle" \
	"Finder" \
	"Google Chrome" \
	"Messages" \
	"Photos" \
	"Rectangle" \
	"SystemUIServer" \
	"VLC" \
	"Transmission" \
	"iCal"; do
	killall "${app}" &> /dev/null
done

# disable photoanalysisd
# https://www.reddit.com/r/MacOS/comments/5887s9/photoanalysisd_macos_sierras_most_contentious_new/
launchctl disable gui/$UID/com.apple.photoanalysisd
launchctl kill -TERM gui/$UID/com.apple.photoanalysisd
defaults write com.apple.iPhoto PKFaceDetectionEnabled 0

# disable spotlight indexing
# can't turn this off because alfred shares the index. bugger
# sudo mdutil -a -i off

echo "Finished MacOS defaults"
