#!/usr/bin/env bash

echo "PHP Setup"

pecl list | grep -q xdebug    || echo '' | pecl install xdebug
pecl list | grep -q memcached || echo '' | pecl install memcached

composer global require --no-interaction \
	require spatie/phpunit-watcher \
  phpstan/phpstan \
  phpunit/phpunit \
  dealerdirect/phpcodesniffer-composer-installer \
  phpcompatibility/php-compatibility \
  flickerleap/phpmd

ln -sf ~/.dotfiles/phpcs.xml ~/phpcs.xml

# Laravel & Valet
# read -pr "Valet (any key)"
# mkdir -p ~/Sites
# composer global require laravel/valet
# export PATH=~/.composer/vendor/bin:$PATH
# valet install
# (cd ~/Sites && valet park)
# valet start
# composer global require tightenco/lambo
