#!/bin/bash

source ~/.dotfiles/Setup/sudo-no-root

echo "Restarting Mac services"

echo "Restarting Dock"
killall Dock

echo "Restarting Finder"
killall Finder

echo "Restarting System UI Server"
killall SystemUIServer

