#!/usr/bin/env bash

# Wait for Dropbox to sync .ssh directory
until [ -d "$HOME/Library/CloudStorage/Dropbox/.ssh" ]; do
  echo "Waiting for Dropbox to sync .ssh..."
  sleep 5
done

if ! [ -L ~/.ssh ]; then
  rm -rf ~/.ssh
  ln -s ~/Library/CloudStorage/Dropbox/.ssh ~/.ssh
fi

sudo find ~/.ssh -type f -exec chmod 0600 {} \;
