#!/bin/bash

# check not run by root
if [ "$(id -u)" == "0" ]; then
  echo "Do not run this script as root" 1>&2
  exit 1
fi

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing sudo time stamp if set, otherwise do nothing.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
