#!/usr/bin/env bash

echo "Tmux & Tmux Plugins"

ln -sf ~/.dotfiles/.tmux.conf ~/.tmux.conf

if [ ! -d ~/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm.git ~/.tmux/plugins/tpm
fi

~/.tmux/plugins/tpm/bin/install_plugins
