#!/bin/bash

source ~/.dotfiles/Setup/sudo-no-root

# Tmux
echo "Tmux & Tmux Plugins"
ln -sf ~/.dotfiles/.tmux.conf ~/.tmux.conf
git clone https://github.com/tmux-plugins/tpm.git ~/.tmux/plugins/tpm
~/.tmux/plugins/tpm/bin/install_plugins

