#!/usr/bin/env bash

echo "NeoVim & NeoVim Plugins"

curl -LO https://github.com/neovim/neovim/releases/download/v0.11.0/nvim-macos-arm64.tar.gz

mkdir -p ~/bin
tar xzf nvim-macos-arm64.tar.gz -C ~/bin/

rm -rf ~/.config/nvim
mkdir -p ~/.config
ln -sf ~/.dotfiles/.config/nvim ~/.config/nvim

nvim --headless -u ~/.config/nvim/init.lua '+Lazy! sync' '+qall'

# Vim
# echo "Vim & Vim Plugins"
# rm -rf ~/.vim
# mkdir -p ~/.vim
# ln -sf ~/.dotfiles/.vim/.vimrc ~/.vimrc
# ln -sf ~/.dotfiles/.vim ~/.vim
# vim -u ~/.vim/.vimrc.plug '+PlugUpdate' '+qall'

