#!/bin/bash

source ~/.dotfiles/Setup/sudo-no-root

# xcode-select --install
mas install 497799835 # because the command line tools never works with node
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -license accept
