#!/usr/bin/env bash

if ! xcode-select -p >/dev/null 2>&1; then
  echo "Installing Xcode Command Line Tools..."
  xcode-select --install

  until xcode-select -p >/dev/null 2>&1; do
    sleep 5
  done
fi
