#!/usr/bin/env bash

# Install full Xcode from App Store
mas install 497799835

sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

# Accept the Xcode/iOS license agreement
if ! sudo xcodebuild -license status >/dev/null 2>&1; then
  sudo xcodebuild -license accept
fi

# Install additional required components
for pkg in /Applications/Xcode.app/Contents/Resources/Packages/*.pkg; do
  sudo installer -pkg "$pkg" -target /
done
