#!/bin/bash

source ~/.dotfiles/Setup/sudo-no-root

echo "Installing Yarn Global Packages"

yarn global add \
  aws-cdk \
  bash-language-server \
  bundle-phobia-cli \
  cfn-lint \
  create-react-app \
  cubejs-cli \
  dockerfile-language-server-nodejs \
  dynamodb-admin \
  dynamodump \
  eslint_d \
  fixjson \
  gzip-size-cli \
  htmlhint \
  http-status-identifier-cli \
  intelephense \
  node-gyp \
  np \
  package-size \
  release-it \
  remotedebug-ios-webkit-adapter \
  uuid-cli
